[package]
name = "book-of-changes"
version = "0.1.0"
authors = ["litttley <617914118@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-rt="1.1.1"
actix-web="2.0.0"
env_logger="0.6"